ALTER TABLE IF EXISTS public.bookings
ADD COLUMN IF NOT EXISTS advance NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS gst NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS deliverables TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS payment_status BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS invoice_sent BOOLEAN DEFAULT false;
